dist: trusty
sudo: false
language: cpp

# addons:
matrix:
  include:
    - env: COMPILER=g++-5  
      addons: { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }

    - env: COMPILER=g++-7  
      addons: { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }

    # - env: COMPILER=clang++-3.8  
    #   addons: { apt: { packages: ["clang-3.8"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-precise-3.8"] } }

    # - env: COMPILER=clang++-5.0  
    #   addons: &defaults { apt: { packages: ["clang-5.0"], sources: ["ubuntu-toolchain-r-test", "llvm-toolchain-trusty-5.0"] } }


install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - ${CXX} --version

script:
    - ./test/run_tests 

